version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    assignees:
      - markheydon
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    assignees:
      - markheydon
    labels:
      - dependencies
    groups:
      devcontainers:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    assignees:
      - markheydon
    labels:
      - dependencies
    groups:
      composer:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    assignees:
      - markheydon
    labels:
      - dependencies
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker-compose
    directory: /.devcontainer
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    assignees:
      - markheydon
    labels:
      - dependencies
    groups:
      docker-compose:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
