name: Trigger Add to Personal Project

on:
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]

jobs:
  add-to-personal-project:
    uses: markheydon/github-workflows/.github/workflows/add-to-personal-project.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${ secrets.PERSONAL_ACCESS_TOKEN }
